# Generated by Django 4.0.4 on 2022-05-17 02:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='PLEASE ONLY ENTER ALPHANUMERIC CHARACTERS', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'PLEASE ONLY ENTER ALPHANUMERIC CHARACTERS')], verbose_name='username'),
        ),
    ]
